### ISSUE TITLE
Custom Field SaleInvoice

### ISSUE THREAD

**Issue by striderxfossility** [picqer/moneybird-php-client#143]
I want to give a value to a custom field.

```
$customField = $moneybird->CustomField());
	$customField->id = ***;
	$customField->name = 'Categorie';
	$customField->value = '4A';
	$customField->source = '4A';

	$customFields = [];
	$customFields[] = $customField;
						
$saleInvoice->custom_fields = $customFields;
```

But it doesnt work.

**Comment by basvandertogt** [comment]
I ran into the same issue. Somebody know a solution?

**Comment by tss68nl** [comment]
Create the custom field in the moneybird webinterface, fill it for at least one item, then download the API response to get the unique identifier number.
Use this Unique ID as the key of the key/value pair you insert into the array, and it will work.

That's a huge workaround, since you have to manually add and find the ID's for it to work, but is manageable if you develop for your own administration.

**Comment by mano-gilissen** [comment]
This issue was never fixed, the Entities/CustomFields class does not contain the "value" field as fillable. For this reason adding a custom field to a new contact as described by @tss68nl does not work. 

After manually adding the "value" field to the CustomFields class everything works as intended.
