### ISSUE TITLE
Stable v1.0 release

### ISSUE THREAD

**Issue by wimski** [picqer/moneybird-php-client#219]
Are there plans to release a stable v1.0 version in the near future which can be used in production?

**Comment by wimski** [comment]
# 👋

**Comment by casperbakker** [comment]
A number is just a number. :) This package is used in production by hundreds of applications. No need to wait for version 1.0.

**Comment by wimski** [comment]
So you don't use semantic versioning then I assume?

https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API _**SHOULD NOT be considered stable**_.

**Comment by casperbakker** [comment]
Not that part, no. Because when we change from 0.x to 1.x, everyone's version stops updating. That is why we usually keep the version of packages in 0.x range when the API is stable and it is already being used by hundreds of people.

When we have to make a cut, because of dependencies or change in the interface, then we probably will change to 1.x versioning to make clear the interface has changed.

Our 0.x for this package is like a 1.x for regular software. No need to wait for it to become more stable.
