### ISSUE TITLE
Can you please update Packagist to v0.34.0?

### ISSUE THREAD

**Issue by markvds** [picqer/moneybird-php-client#272]
Hi!

Somehow the latest tag ([v0.34.0](https://github.com/picqer/moneybird-php-client/releases/tag/v.0.34.0)) didn't make it to Packagist. v0.33.0 is still the [latest version](https://packagist.org/packages/picqer/moneybird-php-client).

Can you please give it a gentle kick?

Thanks!

**Comment by malle-pietje** [comment]
Hi, is there a reason that 0.34.0 is still not available through Packagist?

**Comment by ju5t** [comment]
Sorry for bumping this, but we would like this too. Not a fan of using Github references as they tend to be forgotten.

**Comment by marnickmenting** [comment]
Yes, please!

**Comment by marnickmenting** [comment]
It should update automatically, but probably because of the dot (.) in the tag name after 'v', it does not. @stephangroen Please add the correct tag name.

![CleanShot 2023-02-03 at 16 20 17](https://user-images.githubusercontent.com/10233625/216640238-2e6a6cdd-c94b-47e0-ab67-3176be681c40.png)

Source: https://stackoverflow.com/questions/36142984/packagist-is-not-picking-up-my-new-release-from-github

**Comment by stephangroen** [comment]
Sorry, didn't catch this. Thanks for the mention @marnickmenting! Just added a new release v0.34.1 to be sure it's correct and a new number so no weird issues arise. New version confirmed on [Packagist](https://packagist.org/packages/picqer/moneybird-php-client).

**Comment by marnickmenting** [comment]
Awesome, I can confirm it works now.
